"""Add user profile fields for poker experience

Revision ID: b4af2ef5b301
Revises: 
Create Date: 2025-07-28 19:55:57.824295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4af2ef5b301'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionando apenas os novos campos de usuário (SQLite não suporta ALTER COLUMN)
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('users', sa.Column('poker_experience', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('preferred_games', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('main_stakes', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('poker_goals', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removendo apenas os campos de usuário adicionados
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'country')
    op.drop_column('users', 'poker_goals')
    op.drop_column('users', 'main_stakes')
    op.drop_column('users', 'preferred_games')
    op.drop_column('users', 'poker_experience')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
