"""Add nickname field to users

Revision ID: e45070264a10
Revises: b4af2ef5b301
Create Date: 2025-07-28 20:34:38.247965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45070264a10'
down_revision: Union[str, None] = 'b4af2ef5b301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionando apenas o campo nickname (SQLite não suporta ALTER COLUMN)
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removendo apenas o campo nickname
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
